# Creating Array

In [7]:
#creating numpy array

import numpy as np 
arr=np.array([1,2,3,4,5]) 
print(arr) 
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# 0-D array

In [8]:
arr=np.array(42)
print(arr)

42


# 1-D array

In [9]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


# 2-D array

In [10]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


# 3-D array 

In [11]:
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


# Checking number of Dimension

In [12]:
a=np.array(42)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# Higher dimentional arrays

In [13]:
arr=np.array([1,2,3,4], ndmin=5)

print(arr)
print('number of dimensions :',arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5
