# NumPy Array Reshaping

In [2]:
#Reshaping means changing the shape of an array.
import numpy as np

# Reshape From 1-D to 2-D

In [3]:
arr=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# Reshape From 1-D to 3-D

In [5]:
newarr=arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [7]:
#Check if the returned array is a copy or a view
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.reshape(2,4).base)
#The example above returns the original array, so it is a view.

[1 2 3 4 5 6 7 8]


In [9]:
newarr=arr.reshape(2,2,-1)
print(newarr)
#We can not pass -1 to more than one dimension.

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Flattening the arrays

In [10]:
#Flattening array means converting a multidimensional array into a 1D array.
#We can use reshape(-1) to do this.

arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr=arr.reshape(-1)
print(newarr)


[1 2 3 4 5 6]
