# NumPy Array Iterating

In [1]:
#Iterating means going through elements one by one.
#As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.
#If we iterate on a 1-D array it will go through each element one by one.

# Iterating Arrays

In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,3])
for x in arr:
    print(x)

1
2
3


# Iterating 2-D Arrays

In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [5]:
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


# Iterating 3-D Arrays

In [6]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

for x in arr:
   print(x) 

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [7]:
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


# Iterating Arrays Using nditer()

In [8]:
#The function nditer() is a helping function that can be used 
#from very basic to very advanced iterations. It solves some basic 
#issues which we face in iteration, lets go through it with examples.

# Iterating on Each Scalar Element

In [9]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


# Iterating Array With Different Data Types

In [10]:
arr=np.array([1,2,3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(x)

b'1'
b'2'
b'3'


# Iterating With Different Step Size

In [11]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
    print(x)

1
3
5
7


# Enumerated Iteration Using ndenumerate()

In [16]:
#Enumeration means mentioning sequence number of somethings one by one.
arr=np.array([1,2,3])
for idx, x in np.ndenumerate(arr):
    print(idx,x)

(0,) 1
(1,) 2
(2,) 3
