# NumPy Array Copy vs View

In [1]:
import numpy as np

In [3]:
# The copy SHOULD NOT be affected by the changes made to the original array.
arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [4]:
#Make a view, change the original array, and display both arrays
arr=np.array([1,2,3,4,5])
x=arr.view()
arr[0]=42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [5]:
#Print the value of the base attribute to check if an array owns it's data or not

x=arr.copy()
y=arr.view()

print(x.base)
print(y.base)

#The copy returns None.
#The view returns the original array.

None
[42  2  3  4  5]
