# NumPy Searching Arrays

In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5,4,4])
x=np.where(arr==4)
print(x)
#4 ewa thiyena index tik output krnw

(array([3, 5, 6], dtype=int64),)


In [3]:
arr=np.array([1,2,3,4,5,6,7,8])
x=np.where(arr%2==0)
print(x)

(array([1, 3, 5, 7], dtype=int64),)


# Search Sorted

In [6]:
# indexes where the value 7 should be inserted
arr=np.array([6,7,8,9])
x=np.searchsorted(arr,7)
print(x)

1


# Search From the Right Side

In [7]:
#dakunu paththe idl 7 thiyen index ek
arr=np.array([6,7,8,9])
x=np.searchsorted(arr,7,side='right')
print(x)

2


# Multiple Values

In [9]:
# indexes where the values 2, 4, and 6 should be inserted
arr=np.array([1,3,5,7])
x=np.searchsorted(arr,[2,4,6])
print(x)

[1 2 3]
